version : 3 
services:
drupal:
image: drupal:latest
ports:
-8080:80
volumes:
-./drupal/modules:/var/www/html/modules
-./drupal/profiles:/var/www/html/profiles
-./drupal/themes:/var/www/html/themes
-./drupal/sites:/var/www/html/sites
restart:always
environment:
-MYSQL_HOST=database
-MYSQL_DATABASE=FİNAL
-MYSQL_USER=YAM428
-MYSQL_PASSWORD=030718036
depends_on:
-database

database: 
image:mysql:5.7
ports:
-3306:3306
volumes:
-./mysql:/var/lib/mysql
restart:always
environment:
-MYSQL_DATABASE=FİNAL
-MYSQL_USER=YAM428
-MYSQL_PASSWORD=030718036
-MYSQL_ROOT_PASSWORDE=030718036

nginx:
image: nginx:latest
ports:
- 192.168.0.18:80:80
volumes:
-./nginx/conf.d:/etc/nginx/conf.d
-./nginx/sites:/etc/nginx/sites-available
-./nginx/sites-enabled:/etc/nginx/csites-enabled
restart: always


certbot:
image: certbot/certbot
volumes:
- ./certbot/conf:/etc/letsencrypt
- ./certbot/www:var/www/certbot
depends_on:
-nginx

command: certonly --webroot --webroot-path=/var/lib/www/certbot --email degirmenci.omer@std.izu.edu.tr -- agree-tos --no-eff-email --force-renewal -d degirmenciomer.me -d www.degirmenciomer.me

















































